package com.transport.lib.spring;

import lombok.Getter;

/*
    Class-container for passing list of required client implementations to TransportService bean
 */
@Getter
public class ClientEndpoints {

    // User-provided list of generated by transport-maven-plugin *Transport interfaces
    private Class<?>[] endpoints;

    // Vararg constructor (lombok can't generate it)
    public ClientEndpoints(Class<?>... endpoints) {
        this.endpoints = endpoints;
    }
}
